project_id = "hzviynazgmbvdinbyxbx"

[functions.get-module-flags]
verify_jwt = false

[functions.video-create]
verify_jwt = true

[functions.scenes-generate]
verify_jwt = false

[functions.tts-elevenlabs]
verify_jwt = true

[functions.send-email-campaign]
verify_jwt = true

[functions.email-process-scheduled]
verify_jwt = false

[functions.publish-twitter]
verify_jwt = true

[functions.run-scheduler]
verify_jwt = false

[functions.master-agent]
verify_jwt = true

[functions.research-agent]
verify_jwt = false

[functions.company-research]
verify_jwt = true

[functions.copywriter-agent]
verify_jwt = true

[functions.analyst-agent]
verify_jwt = true

[functions.closer-agent]
verify_jwt = true

[functions.listener-agent]
verify_jwt = true

[functions.messenger-agent]
verify_jwt = true

[functions.performance-analytics]
verify_jwt = true

[functions.test-connectivity]
verify_jwt = false
